import Head from "next/head";
import { useState } from "react";
// Components
import CardTodo from "@/components/CardTodo";
// Models
import User from "@/models/User";
// Utils
import { sortTodos } from "@/utils/functions";
// Next Auth
import { getSession } from "next-auth/react";

export default function Home({ todos }) {
  const [todosData, setTodosData] = useState(todos);
  const fetchData = async () => {
    await fetch("/api/todo")
      .then((res) => res.json())
      .then((data) => setTodosData(data.todos));
  };
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex gap-[1rem] ">
        <div className="w-full">
          <h1 className={`bg-todo w-full p-4 rounded text-center text-white`}>todo</h1>
          <CardTodo todos={todosData["todo"]} Next={"inProgress"} fetchData={fetchData} />
        </div>

        <div className="w-full">
          <h1 className={`bg-inProgress w-full p-4 rounded text-center text-white`}>inProgress</h1>
          <CardTodo
            todos={todosData["inProgress"]}
            Next={"review"}
            Back={"todo"}
            fetchData={fetchData}
          />
        </div>
        <div className="w-full">
          <h1 className={`bg-review w-full p-4 rounded text-center text-white`}>review</h1>
          <CardTodo
            todos={todosData["review"]}
            Next={"done"}
            Back={"inProgress"}
            fetchData={fetchData}
          />
        </div>
        <div className="w-full">
          <h1 className={`bg-done w-full p-4 rounded text-center text-white`}>done</h1>
          <CardTodo todos={todosData["done"]} Back={"review"} fetchData={fetchData} />
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps({ req }) {
  const session = await getSession({ req });
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
        props: {},
      },
    };
  }
  const user = await User.findOne({ email: session.user.email });
  const sortedT = sortTodos(user.todos);
  return {
    props: JSON.parse(JSON.stringify({ todos: sortedT })),
  };
}
